=============================================================================
-- Business Question:
-- How much revenue is generated by new vs returning customers?

-- Dataset:
-- thelook_ecommerce

-- Description:
-- This query segments customers into new and returning groups based on 
-- their purchase behavior and calculates their contribution to total revenue.

-- Metrics:
-- 1. Number of users (by segment)
-- 2. % of total users
-- 3. Total revenue (by segment)
-- 4. % of total revenue

-- Why it matters:
-- This analysis helps determine whether revenue growth is driven by 
-- customer acquisition or retention, and highlights the importance 
-- of repeat customers for overall business performance.

-- Note:
-- Only completed orders are included to ensure accurate revenue calculation.
=============================================================================

WITH order_per_user AS (
  SELECT
    user_id,
    COUNT(DISTINCT order_id) AS orders_per_customer,
    SUM(sale_price) AS revenue_per_customer
  FROM `bigquery-public-data.thelook_ecommerce.order_items`
  WHERE status = "Complete"
  GROUP BY user_id
),

classified_users AS (
  SELECT
    user_id,
    revenue_per_customer,
    CASE
      WHEN orders_per_customer = 1 THEN 'new'
      ELSE 'returning'
    END AS customer_type
  FROM order_per_user
)

SELECT
  customer_type,
  COUNT(*) AS users,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS user_pct,
  ROUND(SUM(revenue_per_customer), 2) AS revenue,
  ROUND(SUM(revenue_per_customer) * 100.0 / SUM(SUM(revenue_per_customer)) OVER(), 2) AS revenue_pct
FROM classified_users
GROUP BY customer_type;
